[package]
name = "cargo-seed"
version = "0.0.1"
description = "Cargo subcommand for seeding data to databases"
repository = "https://github.com/ewrogers/cargo-seed"
readme = "README.md"
license = "MIT"
edition = "2021"
categories = ["development-tools"]

[dependencies]
